### ISSUE TITLE
Only Returns one.

### ISSUE THREAD

**Issue by SimonElbrink** [olusanyaogunjobi/course_manager_assignment#3]
https://github.com/olusanyaogunjobi/course_manager_assignment/blob/2aca1626f6b7a9cb7121d09c4b34fcca51009605/src/main/java/se/lexicon/course_manager_assignment/data/dao/StudentCollectionRepository.java#L52

This method unfortunately returns one Matching student there could potentially be more then one matching.
The Students need to be saved in something and then be returned. 👍🏼 
Similar to how you did it in findAll

I liked the  the email search method, good job!

**Comment by olusanyaogunjobi** [comment]
code reviewed and corrected!
