### ISSUE TITLE
Clear missing default implementation.

### ISSUE THREAD

**Issue by SimonElbrink** [olusanyaogunjobi/course_manager_assignment#4]
https://github.com/olusanyaogunjobi/course_manager_assignment/blob/2aca1626f6b7a9cb7121d09c4b34fcca51009605/src/main/java/se/lexicon/course_manager_assignment/data/dao/StudentCollectionRepository.java#L100

Clear is not implemented. It was to begin with.

**Comment by olusanyaogunjobi** [comment]
done!

**Comment by SimonElbrink** [comment]
Good Job!
