### ISSUE TITLE
Ops. I don't think this is what you want.

### ISSUE THREAD

**Issue by SimonElbrink** [olusanyaogunjobi/course_manager_assignment#5]
https://github.com/olusanyaogunjobi/course_manager_assignment/blob/2aca1626f6b7a9cb7121d09c4b34fcca51009605/src/main/java/se/lexicon/course_manager_assignment/data/dao/CourseCollectionRepository.java#L120

This will always empty all your courses that is saved. i guess this was not you intension.
I Liked how you solved it in studentCollectionRepo. Don't forget to return the result if the deletion was successful or not.

**Comment by olusanyaogunjobi** [comment]
done!

**Comment by olusanyaogunjobi** [comment]
pls, confirm!
