### ISSUE TITLE
Recursive

### ISSUE THREAD

**Issue by SimonElbrink** [olusanyaogunjobi/course_manager_assignment#6]
https://github.com/olusanyaogunjobi/course_manager_assignment/blob/2aca1626f6b7a9cb7121d09c4b34fcca51009605/src/main/java/se/lexicon/course_manager_assignment/model/Course.java#L67

This method setStudent is calling itself. That is nothing we recommend. i understand that you what to set the value. but you need to tell it how. 
How does a normal setter look like? that gives you a sense in right direction.

**Comment by olusanyaogunjobi** [comment]
I have managed to resolve this now.
